In [3]:
import pandas as pd
import numpy as np

### Data Cleaning:



1. #### Quality Issue: 

   * ###### Missing values : 

     * item, quantity, price\_per\_unit, total\_spent, transaction\_date (5 - 10)%
     * payment\_method, location (more then 30%)
     * missing values are identified as (NaN, UNKNOWN, ERROR)
2. #### Structural Issue: 

   * ###### Data Type :

     * item, payment\_method, location -> Object -> category
     * quantity, price\_per\_unit, total\_spent -> Object -> float16
     * transaction\_date -> Object -> datetime

In [ ]:
cafe = pd.read_csv('C:\DSMP\DATA CLEANING\Data-Cleaning-Using-Pandas\dirty_cafe_sales.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\susha\AppData\Local\Temp\ipykernel_5488\517850968.py:1: SyntaxWarning: invalid escape sequence '\D'
  cafe = pd.read_csv('C:\DSMP\DATA CLEANING\Data-Cleaning-Using-Pandas\dirty_cafe_sales.csv')

In [5]:
cafe.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [6]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
cafe.sample(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
3830,TXN_3842567,Salad,1,5.0,5.0,Credit Card,In-store,2023-03-13
4103,TXN_7771526,Juice,1,3.0,3.0,Cash,In-store,2023-04-28
5230,TXN_8534360,Juice,5,3.0,15.0,ERROR,NaN,2023-02-15
7670,TXN_5680687,Salad,4,5.0,UNKNOWN,Credit Card,NaN,2023-11-22
1760,TXN_8092496,Juice,4,3.0,12.0,NaN,In-store,2023-03-11
242,TXN_3786188,Tea,3,1.5,4.5,Credit Card,In-store,2023-10-20
4978,TXN_3301517,Salad,UNKNOWN,5.0,25.0,Credit Card,In-store,2023-04-13
5966,TXN_3321395,Tea,NaN,1.5,1.5,Digital Wallet,Takeaway,2023-07-08
5605,TXN_1206585,Tea,2,1.5,3.0,Cash,NaN,2023-06-29
3341,TXN_7932895,Smoothie,2,4.0,8.0,NaN,In-store,2023-04-04

In [8]:
cafe.columns = cafe.columns.str.lower().str.strip().str.replace(' ','_')

In [9]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9862 non-null   object
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [10]:
cafe['item'].value_counts()

item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [11]:
cafe['payment_method'].value_counts()

payment_method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [12]:
cafe['location'].value_counts()

location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

## Change Data type

### quantity column Object -> float16

In [13]:
index = cafe[cafe['quantity'].isna()].index
cafe.loc[index,'quantity'] = 'NaN'

In [14]:
index = cafe[cafe['quantity'].str.isalpha()].index
cafe.loc[index,'quantity'] = np.nan

In [15]:
cafe['quantity'].isna().sum()

np.int64(479)

In [16]:
cafe['quantity'] = cafe['quantity'].astype('float16')

In [17]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(1), object(7)
memory usage: 566.5+ KB

### perice_per_unit column Object -> float16

In [18]:
index = cafe[cafe['price_per_unit'].isna()].index
cafe.loc[index,'price_per_unit'] = 'NaN'

In [19]:
index = cafe[cafe['price_per_unit'].str.isalpha()].index
cafe.loc[index,'price_per_unit'] = np.nan

In [20]:
cafe['price_per_unit'].isna().sum()

np.int64(533)

In [21]:
cafe['price_per_unit'] = cafe['price_per_unit'].astype('float16')

In [22]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(2), object(6)
memory usage: 507.9+ KB

### total_spent column Object -> float16

In [23]:
index = cafe[cafe['total_spent'].isna()].index
cafe.loc[index,'total_spent'] = 'NaN'

In [24]:
index = cafe[cafe['total_spent'].str.isalpha()].index
cafe.loc[index,'total_spent'] = np.nan

In [25]:
cafe['total_spent'].isna().sum()

np.int64(502)

In [26]:
cafe['total_spent'] = cafe['total_spent'].astype('float16')

In [27]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(3), object(5)
memory usage: 449.3+ KB

### payment_method column object -> category

In [28]:
index = cafe[cafe['payment_method'].isna()].index
cafe.loc[index,'payment_method'] = 'NaN'

In [29]:
payment_method = cafe['payment_method'].unique()

In [30]:
payment_method = payment_method[[0,1,3]].tolist()

In [31]:
index = cafe[~cafe['payment_method'].isin(payment_method)].index

In [32]:
cafe.loc[index,'payment_method'] = np.nan

In [33]:
cafe['payment_method'] = cafe['payment_method'].astype('category')

In [34]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: category(1), float16(3), object(4)
memory usage: 381.1+ KB

### item column Object -> category

In [35]:
index = cafe[cafe['item'].isna()].index
cafe.loc[index,'item'] = 'NaN'

In [36]:
item = cafe['item'].unique()

In [37]:
item = item[[5,7,8]]

In [38]:
index = cafe[cafe['item'].isin(item)].index

In [39]:
cafe.loc[index,'item'] = np.nan

In [40]:
cafe['item'] = cafe['item'].astype('category')

In [41]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: category(2), float16(3), object(3)
memory usage: 313.1+ KB

### location column Object -> category

In [42]:
index = cafe[cafe['location'].isna()].index
cafe.loc[index,'location'] = 'NaN'

In [43]:
location = cafe['location'].unique()

In [44]:
location = location[2:]

In [45]:
index = cafe[cafe['location'].isin(location)].index

In [46]:
cafe.loc[index,'location'] = np.nan

In [47]:
cafe['location'] = cafe['location'].astype('category')

In [48]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6039 non-null   category
 7   transaction_date  9841 non-null   object
dtypes: category(3), float16(3), object(2)
memory usage: 244.9+ KB

### transaction_date column Object -> datetime64

In [49]:
index = cafe[cafe['transaction_date'].isna()].index
cafe.loc[index,'transaction_date'] ='NaN'

In [50]:
index = cafe[cafe['transaction_date'].str.isalpha()].index
cafe.loc[index,'transaction_date'] = np.nan

In [51]:
cafe['transaction_date'] = pd.to_datetime(cafe['transaction_date'])

In [52]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6039 non-null   category
 7   transaction_date  9540 non-null   datetime64[ns]
dtypes: category(3), datetime64[ns](1), float16(3), object(1)
memory usage: 244.9+ KB