In [1]:
import pandas as pd
import numpy as np

### Data Cleaning:



1. #### Quality Issue: 

   * ###### Missing values : 

     * item, quantity, price\_per\_unit, total\_spent, transaction\_date (5 - 10)%
     * payment\_method, location (more then 30%)
     * missing values are identified as (NaN, UNKNOWN, ERROR)
2. #### Structural Issue: 

   * ###### Data Type :

     * item, payment\_method, location -> Object -> category
     * quantity, price\_per\_unit, total\_spent -> Object -> float16
     * transaction\_date -> Object -> datetime

In [2]:
cafe = pd.read_csv('C:\DSMP\DATA CLEANING\Data-Cleaning-Using-Pandas\dirty_cafe_sales.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\susha\AppData\Local\Temp\ipykernel_17360\517850968.py:1: SyntaxWarning: invalid escape sequence '\D'
  cafe = pd.read_csv('C:\DSMP\DATA CLEANING\Data-Cleaning-Using-Pandas\dirty_cafe_sales.csv')

## Data inspection
- .head()
- .sample()
- .values_count()
- .info()

In [3]:
cafe.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [5]:
cafe.sample(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
3918,TXN_2450896,Smoothie,1,4.0,4.0,Digital Wallet,Takeaway,NaN
1385,TXN_9844703,UNKNOWN,2,1.5,3.0,NaN,NaN,2023-05-18
5592,TXN_2919225,Coffee,4,2.0,8.0,Credit Card,Takeaway,2023-02-14
7762,TXN_5349355,NaN,2,5.0,10.0,Digital Wallet,In-store,2023-05-10
5341,TXN_2503128,Cake,1,3.0,3.0,Cash,In-store,2023-01-12
2918,TXN_9365558,Salad,4,5.0,20.0,Credit Card,Takeaway,2023-02-12
3263,TXN_2172960,Smoothie,1,4.0,ERROR,Digital Wallet,NaN,2023-07-04
1049,TXN_7201724,Salad,1,5.0,5.0,Cash,Takeaway,2023-03-20
1123,TXN_3865224,Coffee,3,2.0,6.0,NaN,NaN,2023-07-25
4965,TXN_3484276,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-06-14

In [6]:
cafe.columns = cafe.columns.str.lower().str.strip().str.replace(' ','_')

In [7]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9862 non-null   object
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [8]:
cafe['item'].value_counts()

item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [9]:
cafe['payment_method'].value_counts()

payment_method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [10]:
cafe['location'].value_counts()

location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

## Change Data type

### quantity column Object -> float16

In [11]:
index = cafe[cafe['quantity'].isna()].index
cafe.loc[index,'quantity'] = 'NaN'

In [12]:
index = cafe[cafe['quantity'].str.isalpha()].index
cafe.loc[index,'quantity'] = np.nan

In [13]:
cafe['quantity'].isna().sum()

np.int64(479)

In [14]:
cafe['quantity'] = cafe['quantity'].astype('float16')

In [15]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(1), object(7)
memory usage: 566.5+ KB

### perice_per_unit column Object -> float16

In [16]:
index = cafe[cafe['price_per_unit'].isna()].index
cafe.loc[index,'price_per_unit'] = 'NaN'

In [17]:
index = cafe[cafe['price_per_unit'].str.isalpha()].index
cafe.loc[index,'price_per_unit'] = np.nan

In [18]:
cafe['price_per_unit'].isna().sum()

np.int64(533)

In [19]:
cafe['price_per_unit'] = cafe['price_per_unit'].astype('float16')

In [20]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(2), object(6)
memory usage: 507.9+ KB

### total_spent column Object -> float16

In [21]:
index = cafe[cafe['total_spent'].isna()].index
cafe.loc[index,'total_spent'] = 'NaN'

In [22]:
index = cafe[cafe['total_spent'].str.isalpha()].index
cafe.loc[index,'total_spent'] = np.nan

In [23]:
cafe['total_spent'].isna().sum()

np.int64(502)

In [24]:
cafe['total_spent'] = cafe['total_spent'].astype('float16')

In [25]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float16(3), object(5)
memory usage: 449.3+ KB

### payment_method column object -> category

In [26]:
index = cafe[cafe['payment_method'].isna()].index
cafe.loc[index,'payment_method'] = 'NaN'

In [27]:
payment_method = cafe['payment_method'].unique()

In [28]:
payment_method = payment_method[[0,1,3]].tolist()

In [29]:
index = cafe[~cafe['payment_method'].isin(payment_method)].index

In [30]:
cafe.loc[index,'payment_method'] = np.nan

In [31]:
cafe['payment_method'] = cafe['payment_method'].astype('category')

In [32]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: category(1), float16(3), object(4)
memory usage: 381.1+ KB

### item column Object -> category

In [33]:
index = cafe[cafe['item'].isna()].index
cafe.loc[index,'item'] = 'NaN'

In [34]:
item = cafe['item'].unique()

In [35]:
item = item[[5,7,8]]

In [36]:
index = cafe[cafe['item'].isin(item)].index

In [37]:
cafe.loc[index,'item'] = np.nan

In [38]:
cafe['item'] = cafe['item'].astype('category')

In [39]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: category(2), float16(3), object(3)
memory usage: 313.1+ KB

### location column Object -> category

In [40]:
index = cafe[cafe['location'].isna()].index
cafe.loc[index,'location'] = 'NaN'

In [41]:
location = cafe['location'].unique()

In [42]:
location = location[2:]

In [43]:
index = cafe[cafe['location'].isin(location)].index

In [44]:
cafe.loc[index,'location'] = np.nan

In [45]:
cafe['location'] = cafe['location'].astype('category')

In [46]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6039 non-null   category
 7   transaction_date  9841 non-null   object
dtypes: category(3), float16(3), object(2)
memory usage: 244.9+ KB

### transaction_date column Object -> datetime64

In [47]:
index = cafe[cafe['transaction_date'].isna()].index
cafe.loc[index,'transaction_date'] ='NaN'

In [48]:
index = cafe[cafe['transaction_date'].str.isalpha()].index
cafe.loc[index,'transaction_date'] = np.nan

In [49]:
cafe['transaction_date'] = pd.to_datetime(cafe['transaction_date'])

In [50]:
cafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9031 non-null   category
 2   quantity          9521 non-null   float16
 3   price_per_unit    9467 non-null   float16
 4   total_spent       9498 non-null   float16
 5   payment_method    6822 non-null   category
 6   location          6039 non-null   category
 7   transaction_date  9540 non-null   datetime64[ns]
dtypes: category(3), datetime64[ns](1), float16(3), object(1)
memory usage: 244.9+ KB

In [51]:
cafe.head()

c:\Users\susha\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

## Filling Missing Values on Numerical Columns

### total_spent  = quantity*price_per_unit

In [54]:
tempdf = cafe[cafe['total_spent'].isna()]

In [56]:
total_spent = tempdf['quantity']*tempdf['price_per_unit']

In [58]:
index = tempdf.index

In [60]:
cafe.loc[index,'total_spent'] = total_spent

#### NULL value is reduced form 503 to 40 (reduced by 92%)

In [62]:
cafe['total_spent'].isna().sum()

np.int64(40)

### quantity = total_spent/price_per_unit

In [64]:
cafe['quantity'].isna().sum() # total null values 479

np.int64(479)

In [66]:
tempdf = cafe[cafe['quantity'].isna()]

In [68]:
quantity = tempdf['total_spent']/tempdf['price_per_unit']

In [70]:
index = tempdf.index

In [72]:
cafe.loc[index,'quantity'] = quantity

In [ ]:
cafe['quantity'].isna().sum() # total null values left 38

np.int64(38)

### price_per_unit = total_spent/quantity

In [ ]:
cafe['price_per_unit'].isna().sum() # total null values 533

np.int64(533)

In [75]:
tempdf = cafe[cafe['price_per_unit'].isna()]

In [76]:
price_per_unit = tempdf['total_spent']/tempdf['quantity']

In [78]:
index = tempdf.index

In [79]:
cafe.loc[index,'price_per_unit'] = price_per_unit

In [ ]:
cafe['price_per_unit'].isna().sum() # total null values left 38

np.int64(38)